version: '2.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_CREATE_TOPICS: "topic-getting-things-done:5:1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  command-service:
    image: getting-things-done/eureka/command-service
    mem_limit: 256m
    ports:
      - "8089:8089"
    environment:
      SERVER_PORT: 8089
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
  query-service:
    image: getting-things-done/eureka/query-service
    mem_limit: 256m
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
